### ISSUE TITLE
VPN conflicts with some apps (e.g. Android Auto)

### ISSUE THREAD

**Issue by JohnMaguire** [DefinedNet/mobile_nebula#102]
@brad-defined noticed he was unable to use wireless Android Auto while Nebula was running. I've been unable to connect to certain camera sync apps while Nebula is running.

`VpnService.Builder` offers [a method, addDisallowedApplication()](https://developer.android.com/reference/android/net/VpnService.Builder#addDisallowedApplication(java.lang.String)) in order to configure certain apps to bypass the VPN.

[WireGuard for Android](https://github.com/WireGuard/wireguard-android/blob/4ff564521fd42dcd54c8e0886317cae64d19d6f3/tunnel/src/main/java/com/wireguard/android/backend/GoBackend.java#L265-L266) allows users to select apps from a list to disallow or allow access to the VPN, while [Tailscale](https://github.com/tailscale/tailscale-android/blob/main/android/src/main/java/com/tailscale/ipn/IPNService.java#L70-L83) uses a hardcoded list of known problematic apps to workaround the issue.

**Comment by IanVS** [comment]
I've had trouble using chromecast in the past as well, when nebula vpn was active.

**Comment by JohnMaguire** [comment]
@brad-defined confirmed Android Auto wireless is working - Ian no longer has an Android device to test Chromecast with.
