### ISSUE TITLE
Nebula IP address for static host cannot be input on iPhone

### ISSUE THREAD

**Issue by th** [DefinedNet/mobile_nebula#105]
On iPhone the field for the Nebula IP address in "New Statix Host" opens the wrong input keyboard: only digits 0 through 9 and the comma are there.

The public IP field a bit further down opens the correct full keyboard.

The issue does not exist on iPad.

**Comment by JohnMaguire** [comment]
Hi @th - are you able to provide a screenshot of the wrong keyboard? An iOS version may be helpful too.

The relevant code is here: https://github.com/DefinedNet/mobile_nebula/blob/master/lib/components/IPField.dart#L41

The intent is to open a numeric keyboard that contains a period. Is the problem that the period is missing? I believe one code path calls this with `ipOnly` and the other does not... however, we pass `decimal: true` so I'd expect the period to show up.

**Comment by alexio79** [comment]
Same issue here. I'm attaching a screenshot with wrong keyboard.

![IMG_3C1769447001-1](https://user-images.githubusercontent.com/5347871/218250299-641baf64-b8e5-4a25-84a8-3a5d03eb5741.jpeg)

**Comment by nbrownus** [comment]
@alexio79 can you share what your device locale is and which version of mobile nebula you are running?

**Comment by th** [comment]
In my case it's a German keyboard and it looks like @alexio79's screenshot.

**Comment by alexio79** [comment]
@nbrownus I'm currently running 0.2.0-66 app version based on 1.6.2 Nebula version. The region is Italy.

**Comment by zenithbb** [comment]
@th workaround: you can change iPhone number format and restart, then you can input dot(.), but after restart, the public key will be changed , so you need sign it again
