### ISSUE TITLE
"Share Public Key" not working on iPad

### ISSUE THREAD

**Issue by th** [DefinedNet/mobile_nebula#106]
On iPad in the Certificate screen "Share Public Key" does not do anything. It does not open a share sheet.

But it does work on iPhone.

**Comment by JohnMaguire** [comment]
It looks like we are not passing the required `sharePositionOrigin` for iOS - https://pub.dev/packages/share_plus#:~:text=in%20this%20issue.-,ipad,-share_plus%20requires

**Comment by JohnMaguire** [comment]
@jasikpark reports "Share config" is broken as well.
