### ISSUE TITLE
Hang on "Initializing..."

### ISSUE THREAD

**Issue by Servail** [DefinedNet/mobile_nebula#109]
Doesn't work with two Honor devices for some reason. Shows VPN badge for a moment, then "Initializing..." forever. All possible permissions enabled, every restriction disabled. Works for Xiaomi though.

**Comment by JohnMaguire** [comment]
@Servail Can you please tap "View logs" inside the Nebula site config and share the output?

**Comment by JohnMaguire** [comment]
Closing this one out for inactivity. Please tag me with logs to reopen.
