### ISSUE TITLE
Failed to save the site configuration - com.google.crypto.tink.shaded.protobuf.c0: Protocol message contained an invalid tag (zero).

### ISSUE THREAD

**Issue by johnmaguire** [DefinedNet/mobile_nebula#117]
[From Slack,](https://nebulaoss.slack.com/archives/CS66JRV40/p1668066776550879) Robert Ansel reports:

> Entirely unrelated from the above above, was setting up nebula (app version 0.1.1-59, Nebula version 1.6.1) on a new Pixel 6 running Android 12 today and started getting this error popup:
> 
>
>> Failed to save the site configuration
>> 
>> com.google.crypto.tink.shaded.protobuf.c0: Protocol message contained an invalid tag (zero).
>
> 
> Any idea where that's coming from? If not I'll just open another issue on github (edited) 

5 months later, DaveF reports:

> FYI, I'm in the process of setting up a new Pixel 7 and just encountered this issue. Clearing the cache and storage fixed it for me also. Of note: I let Google auto-install my previous apps as I was setting up the phone and Nebula was one of them. Perhaps that has something to do with it.

And a little extra detail...

> I had a site set up in my old phone, which died. In setting up the new phone, I let Google automatically re-install the apps. It generally did not migrate the app data, just the apps themselves. When I opened Nebula on the new phone, it was empty as you'd expect for a newly-installed app. Trying to add a site resulted in the error in this thread. I tried several times, and twiddled every setting I could in Nebula to see if that would clear it. Ultimately only clearing the app data & cache did it. Also interesting to note was that Android listed ~40MB of app data that would be cleared, even though the app was seemingly newly-installed.
I hope that helps a bit.

**Comment by tzdybal** [comment]
I can confirm that after migrating to new phone error is present. Clearing app data resolved the issue for me.

**Comment by johnmaguire** [comment]
I just upgraded to a Pixel 8 from a Pixel 6. I had only a Defined.net site enrolled, and it does not appear in the site list, which I believe is expected. When I try to enroll a brand new DN host on this phone, I receive this error. I'll dig into this shortly now that I'm able to reproduce.
