### ISSUE TITLE
On iOS 16.5, the VPN cannot be activated

### ISSUE THREAD

**Issue by Virus-V** [DefinedNet/mobile_nebula#131]
I have Mobile Nebula installed on both my iPhone and iPad, but after I upgraded to iOS 16.5, the VPN didn't work anymore. Status has always been Disconnect and I can never activate it.

It's happening on at least two of my devices.
Can you give some advice? Thanks.

**Comment by IanVS** [comment]
Hi, thanks for the report.  We are aware of the issue, and are working on a fix.  Personally, I've found that toggling wifi will usually allow me to connect.

**Comment by nbrownus** [comment]
Looks like we should have a fix out fairly soon, in the mean time toggling the vpn via System Settings -> VPN should work.
