### ISSUE TITLE
Mac VPN nebula app is Not working but iOS app does work

### ISSUE THREAD

**Issue by paragdulam** [DefinedNet/mobile_nebula#140]
Hi, 

I need some help building the Mac app from flutter using the same code base as it's used for iOS. The primary difference is I made a MacOS Compatible framework from nebula folder and referred the makefile.

I was successfully able to add the nebula configuration on Mac Ventura as well but the problem is, the connection was never successfully connected. It sometimes showed Connecting... state forever or just got abruptly to Disconnected state.

I have posted a question on stackoverflow as well regarding the same.
[Mac VPN nebula app is Not working but iOS app does work](https://stackoverflow.com/questions/77341352/mac-vpn-nebula-app-is-not-working-but-ios-app-does-work)

Any help is appreciated. 

Thanks in advance

**Comment by JohnMaguire** [comment]
@paragdulam The mobile nebula app does not support Mac. Just run regular nebula instead: https://github.com/slackhq/nebula
