### ISSUE TITLE
Add apk to releases

### ISSUE THREAD

**Issue by WillPower3309** [DefinedNet/mobile_nebula#150]
Would it be possible to start including a .APK file in new releases of the app? That would provide Android users an easy way to install from release page, and could be very useful for users that like to download their apps from releases through Obtainium (https://github.com/ImranR98/Obtainium/)

**Comment by WillPower3309** [comment]
This would also allow users who do not like having the play store installed (as mentioned by a user in https://github.com/DefinedNet/mobile_nebula/issues/44) to use the app

**Comment by IanVS** [comment]
Included in https://github.com/DefinedNet/mobile_nebula/releases/tag/v0.4.2
