### ISSUE TITLE
listen.host: change default to "[::]"

### ISSUE THREAD

**Issue by jasikpark** [DefinedNet/mobile_nebula#159]
Currently the mobile app does not allow editing the listen.host config value and defaults it to "0.0.0.0" which can cause issues when talking to ipv6 only hosts. 

We should ~~allow editing the value and also~~ change the default to "[::]" to listen on both ipv4 and ipv6.

**Comment by johnmaguire** [comment]
@jasikpark Is there a reason you wanted to allow editing `listen.host` as opposed to simply using `[::]`?

**Comment by jasikpark** [comment]
I suppose there's small reason to need some other value, but it seemed worth allowing 🤷

I'd be happy with just the value change
