### ISSUE TITLE
Relay settings are not converted correctly

### ISSUE THREAD

**Issue by isi-lincoln** [DefinedNet/mobile_nebula#166]
The yaml representation is using `relays` when it should be `relay`.

Offending line:  https://github.com/DefinedNet/mobile_nebula/blob/master/nebula/config.go#L17

How it is used: https://github.com/DefinedNet/nebula/blob/master/main.go#L244C1-L245C6

**Comment by johnmaguire** [comment]
Thanks for the report @isi-lincoln! I believe this ultimately has no impact, as it will use the Nebula defaults:

```
relays:
  am_relay: false
  use_relays: true
```

Instead of:

https://github.com/DefinedNet/mobile_nebula/blob/master/nebula/config.go#L41-L43

That said, I've put up a PR to fix this in the information "View configuration" page!

**Comment by isi-lincoln** [comment]
Hi John,

Yeah, I noticed it was not used, but elected to open an issue in case it does get used by your team in the future.  Thanks for the resolution and follow up.
