### ISSUE TITLE
[Android] Unable to access public internet when private DNS is on.

### ISSUE THREAD

**Issue by zoenglinghou** [DefinedNet/mobile_nebula#17]
When Android uses a private DNS server, specifically when the user specifies a custom server, the device can no longer access public internet once nebula is on. It is likely due to failed DNS resolutions, since https://1.1.1.1 can still be accessed.

Original Issue: https://github.com/slackhq/nebula/issues/349

**Comment by JohnMaguire** [comment]
Closing this issue out, please file a new issue if this behavior is still occurring.
