### ISSUE TITLE
Code license?

### ISSUE THREAD

**Issue by notabeatle** [DefinedNet/mobile_nebula#19]
What license is this code offered under?

**Comment by sebastianschauenburg** [comment]
Is there any discussion about this going on or is it a matter of somebody making a pull request with a LICENSE file? If it's the latter, I wouldn't mind creating a pull request with GPLv3 (yes, I prefer copyleft)

**Comment by KodeZ** [comment]
This has gone unanswered for quite a while. Searching for license gives me a commented out link that does not work, as well as this and a couple of other hits in issues and PRs.

**Comment by IanVS** [comment]
There is intentionally no license to the code in this repository.  See https://choosealicense.com/no-permission/ for what this means.
