### ISSUE TITLE
Can't read Certificate's QR code

### ISSUE THREAD

**Issue by mrtntome** [DefinedNet/mobile_nebula#21]
I generate the pub key in the app and copy it to the CA as `hostx.key`,
then sign a certificate using:
`./nebula-cert sign -name "hostx" -ip XX.XX.XX.XX/24 -in-pub hostx.key`
When I try to read the QR code generated using `qrencode -t asiutf8 hostx.crt` with the app nothing happens.
Also tried generating a .png but with no results.

**Comment by nbrownus** [comment]
Does `-t png` work for you?

**Comment by mrtntome** [comment]
I'll try that next week and bring an update.

**Comment by nbrownus** [comment]
Closing for now, if you are still having issues, please re-open
