### ISSUE TITLE
F-Droid release?

### ISSUE THREAD

**Issue by chayleaf** [DefinedNet/mobile_nebula#44]
Related to #19

F-Droid is an alternative app store for android that provides FLOSS apps. Personally, I don't have Play Store installed at all. Currently this app isn't FLOSS as it doesn't have a license, so nobody can legally do anything to the code in this repository, so first a license would have to be announced.

Other than that, F-Droid releases are fairly straightforward, but an important prerequisite is F-Droid releases not having stuff like Google Play Services (it can be done via a separate build flavor). Everything seems to be fine already, a license just needs to be stated.

More info: https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/ or https://dev.to/sanandmv7/how-to-publish-your-apps-on-f-droid-2epn

**Comment by Nidrop** [comment]
[answer about the license](https://github.com/DefinedNet/mobile_nebula/issues/19#issuecomment-1554451576) . So I think that's a no for fdroid.
But i think we can ask @IzzySoft about his repo. Hi, do you have any concerns about distributing no-license apps?

**Comment by IzzySoft** [comment]
> do you have any concerns about distributing no-license apps?

Yes, I do. Without a proper FOSS license, it's not really FOSS – but rather "code available" and still proprietary with "all rights reserved". So why not simply applying a proper license? [Many to choose from](https://spdx.org/licenses/).

**Comment by Nidrop** [comment]
> So why not simply applying a proper license?
we found out that this was intentional. It doesn't look like the developers are interested in this. So there's nothing more we can do.

**Comment by IzzySoft** [comment]
OK, so that leaves out quite a few potentially interested people – namely those intentionally avoiding all "Google bindings" and stick with FOSS and F-Droid for a reason. Sad – but as you wrote: nothing more we can do.

**Comment by chayleaf** [comment]
> There is intentionally no license to the code in this repository

With that in mind, I'm closing this, I don't understand the point of this repo being posted here at all then

**Comment by IzzySoft** [comment]
It's not illegal. It's just (legally) unclear whom such contributions belong to then – or what happens if you use code from here in your own projects. That's the point of a license, to make that clear.

**Comment by chayleaf** [comment]
It's illegal to release an app without a license if you include other people's unlicensed contributions, and to my knowledge, the devs of this app release it on Play Market

**Comment by IzzySoft** [comment]
IANAL. But anyway, it leaves a situation of uncertainty. And I indeed could imagine that, with evil intent, one could contribute code and then sue the devs when the resulting APK was made public, arguing they wanted that just for their own solution. So both sides could be in trouble here: those contributing to and those using the code. And in the case at hand, those providing the APK as well.

**Comment by JohnMaguire** [comment]
Hi all - I appreciate the disappointment on the lack of an OSS license or F-Droid release. However, I wanted to clear up a couple points to alleviate some concerns raised above.

Defined Networking owns this repository. To date, no PRs by outside contributors have been merged into the repo. That being said, we do require a signed CLA for PRs in order to ensure proper licensing of outside contributions (see https://github.com/DefinedNet/mobile_nebula/pull/104 for an example.)

Thanks for your concern and I hope you enjoy using Nebula.
