### ISSUE TITLE
Routes are not supported with Nebula 1.5.2

### ISSUE THREAD

**Issue by numinit** [DefinedNet/mobile_nebula#51]
Hi there,

I get "routes are not supported on android" with Nebula 1.5.2. Looks like the tun_android changed in 1.5.

**Comment by JohnMaguire** [comment]
@numinit Hey there - it looks like v0.1.0, released upgraded to Nebula v1.6.1 which should support routes on Android again. Care to give it a shot?

**Comment by JohnMaguire** [comment]
Closing this issue out, please tag me if you're still experiencing issues.
