### ISSUE TITLE
Nebula app spins on Android when another VPN app is "always on"

### ISSUE THREAD

**Issue by brad-defined** [DefinedNet/mobile_nebula#60]
We had a couple of reports in Slack about the Nebula app spinning on startup:
https://nebulaoss.slack.com/archives/CRWJJM52B/p1654479054750989
> Hello, I have the Nebula app on Android 11. When I open it, the main page (where I presume sites are listed) continuously spins (loads). Adding a new site doesn't help. Restarting also doesn't help. I don't see any errors, it just loads forever. I imported the device and CA certificates as generated with the CA binary. Am I missing something?

Frank resolved it by ensuring there wasn't another VPN app marked 'Always On'.

https://nebulaoss.slack.com/archives/CS01XE0KZ/p1655050891622509
> Hey, I'm trying to connect my Android phone to my Nebula Network but the app keeps showing the loading symbol. Nothing changes when I'm adding a site

Sebastian reported the same thing, and removing another VPN that's "Always On" resolved it.
https://nebulaoss.slack.com/archives/CS01XE0KZ/p1655052142562449
> OK the problem was that I had another vpn app enabled as always on

**Comment by JohnMaguire** [comment]
The most recent version of Mobile Nebula changed the behavior here slightly, but we can at minimum improve wording here. From Jeff Wright on Slack:

> In case anyone else runs into this issue: if you have another VPN on an Android phone set to Always-on, Nebula Android will fail to connect with a VPN permissions error. Took me a bit to realize what was going on. Said something like "allow VPN permissions when requested" but permissions had never been requested.

[definednetworking.slack.com/archives/CS01XE0KZ/p1681145123777509](https://definednetworking.slack.com/archives/CS01XE0KZ/p1681145123777509)

**Comment by develroo** [comment]
> The most recent version of Mobile Nebula changed the behavior here slightly, but we can at minimum improve wording here. [Detecting a running VPN](https://stackoverflow.com/a/55609059/242129) would probably be even better. At least currently, only one VPN can be active at a time:
> 
> > There can be only one VPN connection running at the same time. The existing interface is deactivated when a new one is created.
> 
> -- https://developer.android.com/reference/android/net/VpnService.html
> 
> From Jeff Wright on Slack:
> 
> > In case anyone else runs into this issue: if you have another VPN on an Android phone set to Always-on, Nebula Android will fail to connect with a VPN permissions error. Took me a bit to realize what was going on. Said something like "allow VPN permissions when requested" but permissions had never been requested.
> 
> [definednetworking.slack.com/archives/CS01XE0KZ/p1681145123777509](https://definednetworking.slack.com/archives/CS01XE0KZ/p1681145123777509)

Just want to add this is not a limit on all devices, only google pure ones. Nether e/OS, Graphene OS or Lineage have these restrictions. But by not given an option to bypass this check, you are effectively locking out all the security conscious users from using your app. Which I would think is basically the target demographic you are looking for.  


Just a thought.
