### ISSUE TITLE
[ios][feature request] need relay config ui or allow config all stuff as a whole for every thing

### ISSUE THREAD

**Issue by congzhangzh** [DefinedNet/mobile_nebula#69]
Hi folks,

First, is that possible to do relay config from advanced UI?
Second, is that possible to allow custom config as a whole, like a config on a laptop, and scan the whole config by QRcode?
It will be very convenient,

Tks,
Cong

**Comment by congzhangzh** [comment]
I want to do some config like https://github.com/slackhq/nebula/blob/master/examples/config.yml#L165

**Comment by JohnMaguire** [comment]
Hi @congzhangzh -

v0.1.0 was released last week and includes support for connecting to remote devices over a relay. This means that if you attempt to access a remote node from your phone, and that remote device contains relays in its configuration, your phone can use the relay to access that remote node.

This does not support relaying _inbound_ to the phone. This isn't likely to be very useful without support for inbound firewall rules. (#45)

Does this satisfy your relay use case, or do you require inbound connectivity?

(As for the request to import the entire config, that's not currently possible unfortunately.)

**Comment by congzhangzh** [comment]
@JohnMaguire cool, seems fit my need, I will have a try lately!

**Comment by JohnMaguire** [comment]
I'm going to close this ticket out as the app supports relays now. We don't have plans to support uploading a config blob but will add more config options where it makes sense in the future as time allows.

Let me know if you run into any issues with the relay support!
