### ISSUE TITLE
ios: have to reconnect daily

### ISSUE THREAD

**Issue by LennyPenny** [DefinedNet/mobile_nebula#74]
so while the app is working great when freshly connected, after a day or so accessing the network stops working. 

Then I have to go into the app again and see that I'm disconnected, or have to disconnect + reconnect. 

Is there a setting I am missing or is this just a limitation of the ios vpn api?

**Comment by JohnMaguire** [comment]
@LennyPenny Hey there, can you check the site logs and see if there's anything interesting after the VPN stops?

**Comment by LennyPenny** [comment]
what do you mean by site logs? on my phone or one of my servers that are part of the network?

**Comment by JohnMaguire** [comment]
If you click on the connection in the mobile app there is an option to view
the Nebula logs.

**Comment by LennyPenny** [comment]
hmm it seems to not happen anymore

I thought I reproduced it but then just opening the app fixed it with nothing in the logs

Closing for now
