### ISSUE TITLE
Lower Android version requirements

### ISSUE THREAD

**Issue by noseshimself** [DefinedNet/mobile_nebula#75]
Don't ask me why but after reinstallation of ChromeOS on my ChromeBook neither version 106 (stable) nor 108 (devel) permit me to reinstall the Nebula Android application. I'm suddenly getting a refusal reasoned "this application is incompatible with your device" yet I know I had it already running on this system.

This usually means that the application has not been compiled for the target CPU (in my case x64), needs a higher version API or installation on non-phones has been forbidden. As it has been working before there must have been a change within the last 18 days that is excluding Android (Intel) now.

Please recompile for Android 9 on 64bit Intel CPU without any restrictions to devices.

**Comment by nbrownus** [comment]
Who is the manufacturer and what model is the chromebook?

**Comment by noseshimself** [comment]
Lenovo Thinkpad C13 Yoga

The Thinkpads are still on Android 9 (it's a bit unclear who is deciding which platforms will be upgraded to Android 11 at which point -- and whether that will be before they are rolling out Android as VM-based subsystem next century).

About 75% of the ChromeOS devices are still on ARC+ with Android 9; a number of them will be updated to Android 11 with ChromeOS 108 (not the Thinkpad C13; I have one running the developer branch) but I had serious problems with ChromeOS being unable to distinguish between multiple Linux containers so I returned to the stable branch and will have to wait even longer.

To explain the request a bit better: Side loading Android apps on ChromeOS is a major pain that will break a lot of the security model (it's a trade-off for being able to do things like route the entire network traffic through an Android app) so I'm limited to Ziti or Nebula if I want to be able to use stock company android devices. After trying both we decided to invest our time in Nebula.

**Comment by noseshimself** [comment]
It would really be nice to push a fast update with lowered API and Android version requirements into the Google Play Store; side loading APKs on ChromeOS has a severe penalty (complete reinstallation) and several users are without any mesh connection for a week now. The alternative would be immediate replacement of the entire mesh...

**Comment by noseshimself** [comment]
>        minSdkVersion 23 //flutter.minSdkVersion
>        targetSdkVersion 31 //flutter.targetSdkVersion

Great. targetSdkVersion 31 will solve my second problem: Getting it as soon as it is pushed to the Play Store because that's a requirement for delivery to current Android versions after 20221101.

Thanks!

**Comment by noseshimself** [comment]
Would you mind building a new release at least for the Google Play Store and pushing it there?

**Comment by nbrownus** [comment]
I have submitted [build 59 v0.1.1](https://github.com/DefinedNet/mobile_nebula/tree/469195cdf711c8828b16b44bc6684ad4005e561c) to the production track. This should resolve your issues with ChromeOS.

**Comment by nbrownus** [comment]
The new build should be live now, if it does not fix your ChromeOS issues, please re-open. Thanks for reporting!

**Comment by noseshimself** [comment]
Arrived in the Play Store today. Working.
